### **1. 기온 CSV 데이터 시각화**

In [ ]:
#코드 7-18
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

In [ ]:
#코드 7-19
import matplotlib.pyplot as plt
import pandas as pd

#데이터를 데이터프레임 형태로 읽어오기
df = pd.read_csv('기온.csv', encoding='cp949')
df.head(3)

In [ ]:
#코드 7-20
df.info()

In [ ]:
#코드 7-21
df2 = df.fillna(method='ffill')
df2.info()

In [ ]:
#코드 7-22
df2.rename(columns={'최저기온(°C)':'min_temp'}, inplace=True)
df2.rename(columns={'평균기온(°C)':'avg_temp'}, inplace=True)
df2.rename(columns={'최고기온(°C)':'max_temp'}, inplace=True)
df2.head(3)

In [ ]:
#코드 7-23
plt.rc('font', family='NanumGothic')
plt.rcParams['axes.unicode_minus'] = False

plt.title('서울시 2022년도 기온 변화')
plt.plot(range(1,len(df2)+1), df2['max_temp'], label='최고기온', c='r')
plt.plot(range(1,len(df2)+1), df2['avg_temp'], label='평균기온', c='y')
plt.plot(range(1,len(df2)+1), df2['min_temp'], label='최저기온', c='b')
plt.xlabel('일')
plt.ylabel('기온')
plt.legend()
plt.show()

In [ ]:
#코드 7-24
df2['일시'] = pd.to_datetime(df2['일시'], format='%Y-%m-%d')
df2['일시']

In [ ]:
#코드 7-25
df3 = df2.set_index('일시')
df3.head(3)

In [ ]:
#코드 7-26
df_Mar = df3[pd.DatetimeIndex(df3.index).month == 3]

In [ ]:
#코드 7-27
plt.title('서울시 2022년도 3월 기온 변화')
plt.plot(range(1,32), df_Mar['max_temp'], label='최고기온', c='r')
plt.plot(range(1,32), df_Mar['avg_temp'], label='평균기온', c='y')
plt.plot(range(1,32), df_Mar['min_temp'], label='최저기온', c='b')

plt.xlabel('3월')
plt.ylabel('기온')
plt.xlim(1,31)
plt.ylim(-7, 22)
plt.legend()
plt.rcParams['figure.figsize'] = (100, 200)

plt.show()
plt.savefig('서울.png')